repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files
    - id: detect-private-key
    - id: detect-aws-credentials
      args: ["--allow-missing-credentials"]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.1
  hooks:
    - id: gitleaks

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
    - id: cargo-check
    - id: clippy
      args: ["--fix", "--allow-dirty", "--allow-staged"]
