[aws]
region = "eu-west-1"
workgroup = "primary"
output_location = "s3://your-athena-results/"
catalog = "AwsDataCatalog"

[app]
query_reuse_time = "1h"
download_dir = ""
max_rows = 1000
history_size = 20
history_fields = ["Id", "Status", "Query", "StartTime", "EndTime", "DataScanned", "Runtime", "OutputLocation"]
