name: Security Audit
on:
  # Run when dependencies are updated
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  
  # Rerun weekly to pick up new advisories (every Monday at midnight)
  schedule:
    - cron: '0 0 * * 1'
  
  # Run manually
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies